const DATA={...window.RW_DATA,groups:window.RW_GROUPS};const S={step:0,gid:null,shown:null,scene:null,customScene:null,sceneTitle:null,safetyMode:false,crisisId:null,rel:{},del:[],emo:[]};const app=document.getElementById('app');
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function panel(k,t,h,c,back=true,next=true){return `<section class="panel"><div class="kicker">${k}</div><h2>${t}</h2><p class="helper">${h}</p>${c}<div class="actions">${back?'<button class="btn secondary" onclick="back()">이전</button>':'<span></span>'}${next?'<button id="next" class="btn primary" onclick="next()">다음</button>':''}</div></section>`}
function prog(){[...document.querySelectorAll('#prog span')].forEach((x,i)=>x.classList.toggle('active',i===S.step))}
function render(){prog();[renderSearch,renderScenes,renderRel,renderDel,renderEmo,renderResult][S.step]()}
function normalizeText(s){return String(s||'').toLowerCase().replace(/[^\uac00-\ud7a3a-z0-9]/g,'')}
function scoreText(q,text){q=normalizeText(q);text=normalizeText(text);if(!q||!text)return 0;if(q===text)return 100;if(text.startsWith(q)||q.startsWith(text))return 82;if(text.includes(q)||q.includes(text))return 68;let common=0;for(const ch of new Set(q))if(text.includes(ch))common++;return Math.round((common/Math.max(new Set(q).size,1))*40)}
function searchAliases(q){q=q.trim();if(!q)return[];const arr=[];for(const g of DATA.groups){for(const a of g.aliases||[]){const score=scoreText(q,a);if(score>=45)arr.push({g,shown:a,score,type:'alias'})}const canonicalScore=scoreText(q,g.canonical);if(canonicalScore>=90)arr.push({g,shown:g.canonical,score:canonicalScore,type:'canonical'})}const seen=new Set();return arr.sort((a,b)=>b.score-a.score).filter(r=>{const k=r.g.id+'|'+r.shown;if(seen.has(k))return false;seen.add(k);return true}).slice(0,20)}
function nearbyGroups(q){q=q.trim();if(!q)return[];const arr=[];for(const g of DATA.groups){let best=scoreText(q,g.canonical);for(const a of g.aliases||[])best=Math.max(best,scoreText(q,a)-8);for(const k of g.keywords||[]){if(normalizeText(q).includes(normalizeText(k))||normalizeText(k).includes(normalizeText(q)))best=Math.max(best,52)}if(best>0)arr.push({g,score:best})}return arr.sort((a,b)=>b.score-a.score).slice(0,8)}
function findCrisis(q){q=normalizeText(q);if(!q)return null;for(const item of DATA.crisis_expressions||[]){const terms=[item.text,...(item.aliases||[])];for(const term of terms){const t=normalizeText(term);if(q===t||q.includes(t)||t.includes(q))return{item,shown:term}}}return null}
function renderSafetyScreen(shown){S.safetyMode=true;S.shown=shown;S.step=5;prog();app.innerHTML=`<section class="panel"><div class="kicker">안전 확인</div><h2>지금은 숨은 뜻보다 안전을 먼저 확인해야 합니다</h2><p class="helper">“${esc(shown)}”는 답답함이나 과장된 표현일 수도 있지만, 실제 위험 신호일 가능성을 먼저 배제해서는 안 됩니다.</p><div class="notice"><strong>지금 바로 확인할 것</strong><br>현재 혼자 있는지, 자신을 해칠 생각이 있는지, 구체적인 계획·수단·시점이 있는지 직접 확인해야 합니다.</div><div class="q"><div class="qt">확인 질문</div><p>“지금 자신을 해칠 생각이 있어?”</p><p>“구체적으로 생각한 방법이나 준비한 것이 있어?”</p><p>“지금 혼자 있어, 아니면 곁에 누가 있어?”</p></div><div class="q"><div class="qt">위험이 임박해 보인다면</div><p>혼자 두지 말고 가까운 보호자·응급서비스·전문기관에 바로 연결해야 합니다.</p><p>‘관심을 끌려는 말’이나 ‘그럴 리 없다’고 단정하지 않습니다.</p></div><div class="notice">이 화면은 일반적인 의미 해석을 제공하지 않습니다. 안전 확인이 끝난 뒤에만 상황과 감정을 다시 살펴보세요.</div><div class="actions"><span></span><button class="btn primary" onclick="restart()">처음으로</button></div></section>`}
function renderSearch(q=''){q=String(q||'');const crisis=findCrisis(q);if(crisis){renderSafetyScreen(q.trim()||crisis.shown);return}const aliasResults=searchAliases(q);let content=`<input id="expressionSearch" class="search" autofocus placeholder="들은 말을 입력하세요" value="${esc(q)}" oninput="renderSearch(this.value)">`;if(!q.trim()){content+=`<div class="notice">검색어를 입력하면 먼저 유사언어 후보가 나타납니다. 해당 표현을 선택하면 선택한 말 그대로 다음 단계로 이동합니다.</div>`}else if(aliasResults.length){content+=`<div class="notice"><strong>입력한 말과 가까운 유사언어를 선택해 주세요.</strong><br>선택한 표현은 상황 선택과 결과 화면까지 그대로 표시됩니다.</div>`;content+=`<div class="grid">`+aliasResults.map(r=>`<button class="card ${S.gid===r.g.id&&S.shown===r.shown?'sel':''}" onclick='pick(${JSON.stringify(r.g.id)},${JSON.stringify(r.shown)})'><strong>${esc(r.shown)}</strong><small>${r.type==='canonical'?'대표 표현':'유사언어'} · 대표 상황 ${r.g.scenes.length}개</small></button>`).join('')+`</div>`}else{const nearby=nearbyGroups(q);content+=`<div class="notice"><strong>입력한 말과 일치하는 유사언어가 아직 없습니다.</strong><br>아래에서 의미가 가장 가까운 대표 표현군을 선택해 주세요.</div>`;content+=nearby.length?`<div class="grid">`+nearby.map(r=>`<button class="card ${S.gid===r.g.id&&S.shown===q?'sel':''}" onclick='pick(${JSON.stringify(r.g.id)},${JSON.stringify(q)})'><strong>${esc(r.g.canonical)}</strong><small>가까운 대표 표현군 후보 · 화면에는 “${esc(q)}” 유지</small></button>`).join('')+`</div>`:`<div class="empty">가까운 대표 표현군도 찾기 어렵습니다.<br>다른 핵심 단어로 다시 입력해 주세요.</div>`}app.innerHTML=panel('1단계 · 표현','어떤 말을 들었나요?','검색창에 들은 말을 입력한 뒤, 유사언어 또는 가까운 대표 표현군을 선택합니다.',content,false,true);enable(!!S.gid);const input=document.getElementById('expressionSearch');if(input){input.focus();const len=input.value.length;input.setSelectionRange(len,len)}}
function pick(id,shown){S.gid=id;S.shown=shown;S.safetyMode=false;S.crisisId=null;S.scene=null;S.customScene=null;S.sceneTitle=null;S.rel={};S.del=[];S.emo=[];renderSearch(shown)}
function renderScenes(){const g=DATA.groups.find(x=>x.id===S.gid);const primary=g.scenes.map(s=>`<button class="card ${S.scene===s.scene_id?'sel':''}" onclick='pickScene(${JSON.stringify(s.scene_id)},${JSON.stringify(s.scene_title)})'><strong>${esc(s.scene_title)}</strong><small>“${esc(S.shown)}”가 이 장면에서 어떻게 작동했는지 살펴봅니다.</small></button>`).join('');const allGroups=DATA.situation_groups.map(group=>`<details class="q"><summary class="qt">${esc(group.title)}</summary><div class="grid" style="margin-top:10px">${group.scenes.map(s=>`<button class="card ${S.scene===s.id?'sel':''}" onclick='pickScene(${JSON.stringify(s.id)},${JSON.stringify(s.title)})'><strong>${esc(s.title)}</strong><small>${esc(s.selection)}</small></button>`).join('')}</div></details>`).join('');const custom=S.scene==='CUSTOM';const content=`<div class="grid">${primary}</div><div class="notice"><strong>가까운 상황이 없나요?</strong><br>아래 상황군을 펼쳐 고르거나 직접 입력해 계속할 수 있습니다.</div><div>${allGroups}</div><div class="q"><div class="qt">직접 상황 입력</div><textarea id="customSceneInput" class="search" style="min-height:100px;resize:vertical" placeholder="그 말이 나오기 직전에 어떤 일이 있었는지 적어 주세요.">${custom?esc(S.customScene||''):''}</textarea><button class="btn secondary" onclick="useCustomScene()">이 상황으로 계속하기</button>${custom?'<div class="notice">미분류 상황으로 선택되었습니다. 결과의 확신 수준은 낮게 표시됩니다.</div>':''}</div>`;app.innerHTML=panel('2단계 · 상황',`“${esc(S.shown)}”가 나온 장면은 무엇에 가까웠나요?`,'대표 상황이 맞지 않으면 가까운 상황군 또는 직접 입력을 사용할 수 있습니다.',content);enable(!!S.scene)}
function pickScene(id,title){S.scene=id;S.customScene=null;S.sceneTitle=title;renderScenes()}
function useCustomScene(){const value=(document.getElementById('customSceneInput')?.value||'').trim();if(!value){alert('상황을 한 문장 이상 입력해 주세요.');return}S.scene='CUSTOM';S.customScene=value;S.sceneTitle=value;renderScenes()}
function renderRel(){let c='';for(const q of DATA.conditions){c+=`<div class="q"><div class="qt">${q.question}</div>`;for(const o of q.options)c+=`<label class="option"><input type="radio" name="${q.id}" ${S.rel[q.id]?.id===o.id?'checked':''} onchange="setRel('${q.id}','${o.id}',${o.score})"><span>${o.label}</span></label>`;c+='</div>'}app.innerHTML=panel('3단계 · 관계','관계의 어떤 조건이 의미를 바꿨나요?','최소 4개 질문에 답해 주세요.',c);enable(Object.keys(S.rel).length>=4)}
function setRel(q,i,s){S.rel[q]={id:i,score:s}}
function renderDel(){let c=DATA.delivery.map(d=>`<label class="option"><input type="checkbox" ${S.del.includes(d.id)?'checked':''} onchange="tog('del','${d.id}')"><span>${d.name}</span></label>`).join('');app.innerHTML=panel('4단계 · 말하기 방식','그 말은 어떻게 들렸나요?','기억나는 관찰 단서만 복수 선택합니다. 기억나지 않으면 선택하지 않고 넘어가도 됩니다.',c)}
function renderEmo(){let c='<div class="grid">'+DATA.emotions.map(e=>`<button class="card ${S.emo.includes(e.id)?'sel':''}" onclick="emo('${e.id}')"><strong>${e.name}</strong><small>상대의 실제 감정으로 확정하지 않습니다.</small></button>`).join('')+'</div><div class="notice">최대 2개. 모르겠다면 건너뛰세요.</div>';app.innerHTML=panel('5단계 · 감정','어떤 감정의 기운이 느껴졌나요?','가장 약한 보조 단서입니다. 선택하지 않아도 결과를 볼 수 있습니다.',c)}
function tog(k,id){S[k]=S[k].includes(id)?S[k].filter(x=>x!==id):[...S[k],id]}
function emo(id){if(S.emo.includes(id))S.emo=S.emo.filter(x=>x!==id);else if(S.emo.length<2)S.emo.push(id);renderEmo()}
function rank(){const g=DATA.groups.find(x=>x.id===S.gid);const sc=S.scene==='CUSTOM'?null:g.scenes.find(x=>x.scene_id===S.scene);const scores={};Object.keys(DATA.templates).forEach(f=>scores[f]=0);if(sc)sc.function_ids.forEach((f,i)=>scores[f]+=4-i*.5);else['F04','F05','F07','F10','F01'].forEach((f,i)=>scores[f]+=2-i*.2);const r=S.rel,d=new Set(S.del),e=new Set(S.emo);if(r.R03?.id==='repeated'){scores.F06+=3;scores.F12+=1}if(r.R04?.id==='unsafe'){scores.F05+=3;scores.F07+=2}if(r.R01?.id==='none'||r.R01?.id==='limited')scores.F08+=3;if(r.R02?.id==='strong')scores.F08+=3;if(r.R06?.id==='none'){scores.F06+=3;scores.F09+=1}const dm={D01:['F06','F07'],D02:['F08','F09'],D03:['F01','F05'],D04:['F08','F10'],D05:['F03','F13'],D06:['F12','F09'],D07:['F03','F04'],D08:['F04','F06'],D09:['F02','F05'],D10:['F06','F07'],D11:['F06','F14'],D12:['F04','F07']};for(const x of d)for(const f of dm[x]||[])scores[f]+=2;const em={G01:['F05','F11'],G02:['F09','F12'],G03:['F07','F11'],G04:['F02','F14'],G08:['F03','F04'],G09:['F04','F06'],G10:['F06','F07'],G11:['F01','F14'],G14:['F13','F03']};for(const x of e)for(const f of em[x]||[])scores[f]+=1;return Object.entries(scores).sort((a,b)=>b[1]-a[1]).slice(0,3)}
function renderResult(){const g=DATA.groups.find(x=>x.id===S.gid);const sc=S.scene==='CUSTOM'?null:g.scenes.find(x=>x.scene_id===S.scene);const sceneLabel=S.scene==='CUSTOM'?(S.customScene||'직접 입력한 상황'):sc.scene_title;const rs=rank(),chips=[`표현: ${S.shown}`,`상황: ${sceneLabel}`];const cards=rs.map(([f,s],i)=>{const t=DATA.templates[f];const cert=S.scene==='CUSTOM'?'조심스럽게 볼 필요가 있습니다':(s>=9?'가능성이 비교적 큽니다':s>=6?'가능성 중 하나입니다':'조심스럽게 볼 필요가 있습니다');return `<article class="result"><span class="badge">${cert}</span><h3>${i+1}. ${t.title}</h3><p>${t.summary}</p><p><span class="label">이유</span><br>${t.why}</p><p><span class="label">다르게 읽힐 가능성</span><br>${t.counter}</p><p><span class="label">확인해 볼 말</span><br>${t.check}</p></article>`}).join('');app.innerHTML=`<section class="panel"><div class="kicker">6단계 · 결과</div><h2>“${esc(S.shown)}”는 이렇게 작동했을 가능성이 있습니다</h2><p class="helper">대표 표현군은 내부 계산에만 사용하며, 선택한 실제 표현을 유지합니다.</p><div class="chips">${chips.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div>${cards}${S.scene==='CUSTOM'?'<div class="notice"><strong>미분류 상황 결과입니다.</strong><br>대표 상황 데이터가 없어 관계 조건과 말하기 방식 중심으로 낮은 확신의 가능성을 보여 줍니다.</div>':''}<div class="notice">상대의 속마음을 판정하지 않습니다. 가능한 뜻을 비교하고 확인 질문으로 다시 살펴보세요.</div><div class="actions"><button class="btn secondary" onclick="back()">이전</button><button class="btn primary" onclick="restart()">처음부터</button></div></section>`}
function enable(v){let b=document.getElementById('next');if(b)b.disabled=!v}function next(){if(S.step===0&&!S.gid)return;if(S.step===1&&!S.scene)return;if(S.step===2&&Object.keys(S.rel).length<4)return;S.step=Math.min(5,S.step+1);render();scrollTo(0,0)}function back(){S.step=Math.max(0,S.step-1);render();scrollTo(0,0)}function restart(){Object.assign(S,{step:0,gid:null,shown:null,scene:null,customScene:null,sceneTitle:null,safetyMode:false,crisisId:null,rel:{},del:[],emo:[]});render();scrollTo(0,0)}render();